version: '{build}'

branches:
  only:
    - master

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"
  
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 12 2013"

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - md build
  - cd build
  - cmake --version
  - cmake -G "%GENERATOR%" -A "%PLATFORM%" ..

build:
  project: build/getoptwin.sln
  parallel: true

matrix:
  fast_finish: true
